apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mynodeapp
spec:
  analysis:
    successfulRunHistoryLimit: 3
    unsuccessfulRunHistoryLimit: 3

  selector:
    matchLabels:
      app: mynodeapp

  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
        - name: mynodeapp
          image: mynodeapp
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 10m

  rollbackWindow:
    revisions: 3

  strategy:
    blueGreen:
      activeService: rollout-mynodeapp-active # <- matches Active Service metadata
      previewService: rollout-mynodeapp-preview # <- matches Preview Service metadata

      prePromotionAnalysis:
        templates:
          - templateName: pre-promotion-analysis
        args:
          - name: rollout-mynodeapp-preview

      postPromotionAnalysis:
        templates:
          - templateName: post-promotion-analysis

      previewReplicaCount: 2
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      scaleDownDelaySeconds: 30

      # 0 means not to scale down
      abortScaleDownDelaySeconds: 30
